image:
  repository: lscr.io/linuxserver/bazarr
  tag: 1.2.0

ingress:
  main:
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    enabled: true
    hosts:
      - host: "bazarr.${duckdns_domain}.duckdns.org"
        paths:
        - path: /
    tls:
      - hosts:
          - "bazarr.${duckdns_domain}.duckdns.org"
        secretName: tls-bazarr-ingress
