bazarr:
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: 1.2.0

  env:
    PGID: 1001
    PUID: 1001
    TZ: ${timezone}
    
  persistence:
    config:
      enabled: true
      existingClaim: bazarr-config
    downloads:
      enabled: true
      existingClaim: media

  initContainers:
      update-volume-permission:
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /config  && mkdir -p /downloads/bazarr && chown -R 1001:1001 /downloads/bazarr"]

        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads 
          mountPath: /downloads 
        securityContext:
          runAsUser: 0