nzbget:
  image:
    repository: lscr.io/linuxserver/nzbget
    tag: 21.1.20230119

  
    
  persistence:
    config:
      enabled: true
      existingClaim: nzbget-config
    downloads:
      enabled: true
      existingClaim: media

  initContainers:
      update-volume-permission:
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /config  && mkdir -p /downloads/nzbget && chown 1001:1001 /downloads/nzbget"]

        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads 
          mountPath: /downloads 
        securityContext:
          runAsUser: 0