apiVersion: batch/v1
kind: Job
metadata:
  name: install-ha-plugins
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1" 
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: install-ha-plugins
    spec:
      volumes:
        - name: ha-config
          persistentVolumeClaim:
            claimName: ha-config
      containers:
        - name: install-ha-plugins
          image: bash
          command:
            - bash
            - "-c"
            - "cd /config && wget -O - https://get.hacs.xyz | bash -"
          volumeMounts:
            - name: ha-config
              mountPath: "/config"
      restartPolicy: Never
  backoffLimit: 1
