---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  users_database.yml: {{ .Values.authelia_users | toYaml | trim | b64enc | quote }}

---
