apiVersion: v2
name: authelia-umbrella
version: 0.0.0
dependencies:
  - name: authelia
    repository: https://charts.authelia.com
    version: 0.8.57
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.15.2