image:
  repository: lscr.io/linuxserver/radarr
  tag: 4.3.2.6857-ls167

env:
  PGID: 1001
  PUID: 1001
  
ingress:
  main:
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    enabled: true
    hosts:
      - host: "radarr.${duckdns_domain}.duckdns.org"
        paths:
        - path: /
    tls:
      - hosts:
          - "radarr.${duckdns_domain}.duckdns.org"
        secretName: tls-radarr-ingress

initContainers:
  update-volume-permission:
    image: busybox
    command: ["sh", "-c", "chmod -R 777 /config  && mkdir -p /downloads/radarr && chown -R 1001:1001 /downloads/radarr"]

    volumeMounts:
    - name: config
      mountPath: /config
    - name: downloads 
      mountPath: /downloads 
    securityContext:
      runAsUser: 0

persistence:
  config:
    enabled: true
    existingClaim: radarr-config
  downloads:
    enabled: true
    existingClaim: media