image:
  repository: lscr.io/linuxserver/ombi
  tag: latest

ingress:
  main:
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    enabled: true
    hosts:
      - host: "ombi.${duckdns_domain}.duckdns.org"
        paths:
        - path: /
    tls:
      - hosts:
          - "ombi.${duckdns_domain}.duckdns.org"
        secretName: tls-ombi-ingress

initContainers:
  update-volume-permission:
    image: busybox
    command: ["sh", "-c", "chmod -R 777 /config"]

    volumeMounts:
    - name: config
      mountPath: /config
    securityContext:
      runAsUser: 0

persistence:
  config:
    enabled: true
    existingClaim: ombi-config