jellyseerr:
  image:
    # -- image repository
    repository: fallenbagel/jellyseerr
    # -- image tag
    # @default -- chart.appVersion
    tag: 1.7.0
    # -- image pull policy
    pullPolicy: IfNotPresent

  # -- environment variables. See [image docs](https://jellyfin.org/docs/general/administration/configuration.html) for more details.
  # @default -- See below
  env:
    # -- Set the container timezone
    # GIT_COMMIT: main
    LOG_LEVEL: debug

  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 5055

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: true
      existingClaim: jellyseerr-config
      mountPath: /app/config


