amd-gpu:

  namespace: kube-system
  nfd:
    enabled: true


  lbl:
    image:
      repository: docker.io/rocm/k8s-device-plugin
      tag: "labeller-1.25.2.5"
    resources: {}

  imagePullSecrets: []

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL

  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists

  node_selector:
    feature.node.kubernetes.io/pci-0300_1002.present: "true"
    kubernetes.io/arch: amd64
