loki:
  backend:
    replicas: 1
    nodeSelector:
      # kubernetes.io/hostname: ${master_hostname}
      kubernetes.io/arch : amd64

  gateway:
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: loki.${duckdns_domain}.duckdns.org
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: tls-loki-ingress
          hosts:
            - loki.${duckdns_domain}.duckdns.org