apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: workflow-admin
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - clusterworkflowtemplates
  - cronworkflows
  - workflowtemplates
  - eventsources
  - sensors
  - workfloweventbindings
  verbs:
  - list
  - update
  - watch