games-on-whales:

  nodeSelector:
    priority: ${priority}
  
  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        # traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "GOW"
        gethomepage.dev/description: "Streams graphic applications/games"
        gethomepage.dev/group: "Home Services"
        gethomepage.dev/icon: "https://artifacthub.io/image/af0a46a7-596b-4d29-b1bc-9ed7ba9e0e1d@1x"
      enabled: true
      hosts:
        - host: "gow.${domain}"
          paths:
          - path: /
      tls:
        - hosts:
            - "gow.${domain}"
          secretName: tls-gow-ingress

  sunshine:
    image:
      # -- sunshine image repository
      repository: ghcr.io/games-on-whales/sunshine
      # -- sunshine image tag
      tag: master
      # -- sunshine image pull policy
      pullPolicy: IfNotPresent
    # -- sunshine web interface user
    user: admin
    # -- sunshine web interface pasword
    password: admin
    # -- sunshine log level
    logLevel: debug
    # -- sunshine additional env settings
    env:
      TZ: ${timezone}
      PUID: 1001
      PGID: 1001
  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  # persistence:
  #   home:
  #     enabled: true
  #     type: emptyDir
  #     mountPath: /home/retro

  # -- (object) Pass GPU resources to Xorg, steam and retroarch containers
  # See Custom configuration section in the Readme
  graphic_resources:

  %{ if gpu == "amd" }
  resources:
    requests:
      cpu: 10m
      memory: 127M
    limits:
      amd.com/gpu: 1
      cpu: 44m
      memory: 513M
  %{ endif }
  %{ if gpu == "intel" }
  resources:
    requests:
      cpu: 10m
      memory: 127M
    limits:
      gpu.intel.com/i915: "1"
      cpu: 44m
      memory: 513M
  %{ endif }
  # Generating persistence config from applications.yaml
  ${indent(2,yamlencode({persistence: { for key, value in storage: key => {"enabled":true,"existingClaim":try(value.name,null),"mountPath": try(value.mountPath,null),"subpath": try(value.subpath,null)}}}))}