loki:
  loki:
    # Disable multi-tenant support
    auth_enabled: false

    # S3 backend storage configuration
    storage:
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules

  # Configuration for the write
  write:
    # Number of replicas for the write
    replicas: 1
    persistence:
      # -- Size of persistent disk
      size: 10Gi

    # Enable environment variables in config file
    # https://grafana.com/docs/loki/latest/configuration/#use-environment-variables-in-the-configuration
    # extraArgs:
    #   - '-config.expand-env=true'
    # extraEnv:

  # Configuration for the read
  read:
    # Number of replicas for the read
    replicas: 1
    persistence:
      # -- Size of persistent disk
      size: 10Gi

    # Enable environment variables in config file
    # https://grafana.com/docs/loki/latest/configuration/#use-environment-variables-in-the-configuration
  backend:
    # Number of replicas for the read
    persistence:
      # -- Size of persistent disk
      enableStatefulSetAutoDeletePVC: false
      
  # Configuration for the gateway
  gateway:
    # -- Specifies whether the gateway should be enabled
    enabled: true
    # -- Number of replicas for the gateway
    replicas: 1

  # Disable mino installation
  minio:
    enabled: false

  # Disable self-monitoring
  monitoring:
    selfMonitoring:
      enabled: true
      grafanaAgent:
        installOperator: true
    lokiCanary:
        enabled: true

  # Disable helm-test
  test:
    enabled: false