# adguard-home.yaml

image:
  tag: v0.106.3

controller:
  replicas: 1

initContainers:
  copy-configmap:
    image: busybox
    command:
    - "sh"
    - "-c"
    - |
      mkdir -p /opt/adguardhome/conf
      cp /tmp/AdGuardHome.yaml /opt/adguardhome/conf/AdGuardHome.yaml
    volumeMounts:
    - name: adguard-home-config
      mountPath: /tmp/AdGuardHome.yaml
      subPath: AdGuardHome.yaml
    - name: config
      mountPath: /opt/adguardhome/conf
    securityContext:
      runAsUser: 0

nodeSelector:
  priority: critical

ingress:
  main:
    enabled: true
    annotations:
      # traefik.ingress.kubernetes.io/router.middlewares: internal-services-error-pages@kubernetescrd,internal-services-whitelist@kubernetescrd
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Adguard Home"
      gethomepage.dev/group: "Internal"
      gethomepage.dev/icon: "adguard-home.png"
      gethomepage.dev/widget.type: "adguard"
      gethomepage.dev/widget.url: "http://adguard-adguard-home.services.svc.cluster.local:3000"

    hosts:
      - host: "adguard.${domain}.duckdns.org"
        paths:
        - path: /
    tls:
      - hosts:
          - "adguard.${domain}.duckdns.org"
        secretName: tls-adguard-ingress
service:
  dns-tcp:
    enabled: true
    type: LoadBalancer
    ports:
      dns-tcp:
        enabled: true
        port: 53
        protocol: TCP
        targetPort: 53
    externalTrafficPolicy: Local
  dns-udp:
    enabled: true
    type: LoadBalancer
    ports:
      dns-udp:
        enabled: true
        port: 53
        protocol: UDP
        targetPort: 53
    externalTrafficPolicy: Local

persistence:
  config:
    enabled: true
    type: emptyDir

prometheus:
  serviceMonitor:
    enabled: false
    interval: 30s
    additionalLabels: {}

config: |
  bind_host: 0.0.0.0
  bind_port: 3000
  beta_bind_port: 0
  users: []
  http_proxy: ""
  language: en
  rlimit_nofile: 0
  debug_pprof: false
  web_session_ttl: 720
  dns:
    bind_host: 0.0.0.0
    port: 53
    statistics_interval: 3
    querylog_enabled: true
    querylog_file_enabled: true
    querylog_interval: 90
    querylog_size_memory: 1000
    anonymize_client_ip: false
    protection_enabled: true
    blocking_mode: default
    blocking_ipv4: ""
    blocking_ipv6: ""
    blocked_response_ttl: 10
    parental_block_host: family-block.dns.adguard.com
    safebrowsing_block_host: standard-block.dns.adguard.com
    ratelimit: 0
    ratelimit_whitelist: []
    refuse_any: true
    upstream_dns:
    - tls://1dot1dot1dot1.cloudflare-dns.com
    - https://cloudflare-dns.com/dns-query
    upstream_dns_file: ""
    bootstrap_dns:
    - 9.9.9.10
    - 149.112.112.10
    - 2620:fe::10
    - 2620:fe::fe:10
    all_servers: false
    fastest_addr: false
    allowed_clients: []
    disallowed_clients: []
    blocked_hosts: []
    cache_size: 4194304
    cache_ttl_min: 0
    cache_ttl_max: 0
    bogus_nxdomain: []
    aaaa_disabled: false
    enable_dnssec: false
    edns_client_subnet: false
    max_goroutines: 300
    ipset: []
    filtering_enabled: true
    filters_update_interval: 24
    parental_enabled: false
    safesearch_enabled: false
    safebrowsing_enabled: true
    safebrowsing_cache_size: 1048576
    safesearch_cache_size: 1048576
    parental_cache_size: 1048576
    cache_time: 30
    rewrites: ${dns_rewrites}
      

    blocked_services: []
    customresolver: null
  tls:
    enabled: false
    server_name: ""
    force_https: false
    port_https: 443
    port_dns_over_tls: 853
    port_dns_over_quic: 784
    port_dnscrypt: 0
    dnscrypt_config_file: ""
    allow_unencrypted_doh: false
    strict_sni_check: false
    certificate_chain: ""
    private_key: ""
    certificate_path: ""
    private_key_path: ""
  filters:
    - enabled: true
      url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
      name: AdGuard DNS filter
      id: 1
    - enabled: true
      url: https://adaway.org/hosts.txt
      name: AdAway
      id: 2
    - enabled: true
      url: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      name: MalwareDomainList.com Hosts List
      id: 3
    - enabled: true
      url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      name: MalwareDomainList.com Hosts List
      id: 4
    - enabled: true
      url: http://sysctl.org/cameleon/hosts
      name: MalwareDomainList.com Hosts List
      id: 5
    - enabled: true
      url: https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
      name: MalwareDomainList.com Hosts List
      id: 6
    - enabled: true
      url: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
      name: MalwareDomainList.com Hosts List
      id: 7
  whitelist_filters: []
  user_rules: []
  dhcp:
    enabled: false
    interface_name: ""
    dhcpv4:
      gateway_ip: ""
      subnet_mask: ""
      range_start: ""
      range_end: ""
      lease_duration: 86400
      icmp_timeout_msec: 1000
      options: []
    dhcpv6:
      range_start: ""
      lease_duration: 86400
      ra_slaac_only: false
      ra_allow_slaac: false
  clients: []
  log_compress: false
  log_localtime: false
  log_max_backups: 0
  log_max_size: 100
  log_max_age: 3
  log_file: ""
  verbose: false
  schema_version: 7