home-assistant:
  # home-assistant.yaml
  image:
    repository: linuxserver/homeassistant
    tag: 2023.11.0
  initContainers:
    copy-configmap:
      image: busybox
      command:
      - "sh"
      - "-c"
      - |
        cp /ha-config/configuration.yaml /config/configuration.yaml
      volumeMounts:
      - name: config
        mountPath: /config
      - name: config-custom
        mountPath: /ha-config
      
      securityContext:
        runAsUser: 0

    # install-hasc:
    #   image: bash
    #   command:
    #   - "bash"
    #   - "-c"
    #   - |
    #     cd /config && ls && wget -O - https://get.hacs.xyz | bash -
    #   volumeMounts:
    #   - name: config
    #     mountPath: /config

    #   securityContext:
    #     runAsUser: 0


  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet





  securityContext:
    privileged: true

