home-assistant:
  # home-assistant.yaml
  image:
    repository: lscr.io/linuxserver/homeassistant
    tag: 2023.4.4

  initContainers:
    copy-configmap:
      image: busybox
      command:
      - "sh"
      - "-c"
      - |
        cp /ha-config/configuration.yaml /config/configuration.yaml
      volumeMounts:
      - name: config
        mountPath: /config
      - name: config-custom
        mountPath: /ha-config
      
      securityContext:
        runAsUser: 0

    # install-hasc:
    #   image: bash
    #   command:
    #   - "bash"
    #   - "-c"
    #   - |
    #     cd /config && ls && wget -O - https://get.hacs.xyz | bash -
    #   volumeMounts:
    #   - name: config
    #     mountPath: /config

    #   securityContext:
    #     runAsUser: 0


  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  persistence:
    config:
      enabled: true
      existingClaim: ha-config
    config-custom:
      enabled: true
      type: configMap
      name: config-file
    # usb:
    #   enabled: true
    #   type: hostPath
    #   hostPath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2434151-if00
    #   mountPath: /dev/ttyUSB0



  securityContext:
    privileged: true

