grafana:
  name: grafana
  namespace: monitoring
  deploy: true
  volumes:
    config:
      enabled: true
      name: grafana-config
      size: 1Gi
      access_modes:
        - ReadWriteOnce
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}

kube-prometheus-stack:
  name: kube-prometheus-stack
  namespace: monitoring
  server_side: "false"
  deploy: true
  volumes: {}
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}
    master_hostname: ${master_hostname}

homepage:
  name: homepage
  namespace: services
  deploy: true
  volumes: {}
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}
    master_hostname: ${master_hostname}

dex:
  name: dex
  namespace: services
  deploy: false
  volumes: {}
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}
    master_hostname: ${master_hostname}


loki:
  name: loki
  namespace: monitoring
  deploy: true
  volumes: {}
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}
    master_hostname: ${master_hostname}

promtail:
  name: promtail
  namespace: monitoring
  deploy: true
  volumes: {}
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}
    master_hostname: ${master_hostname}

plex:
  name: plex
  namespace: services
  deploy: true
  volumes:
    config:
      enabled: false
      name: plex-config
      size: 5Gi
      access_modes:
        - ReadWriteOnce
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}
    allowed_networks: ${allowed_networks} 
    plex_claim_token: ${plex_claim_token} 
    api_key: ${api_keys["plex_key"]}


jellyseerr:
  name: jellyseerr
  namespace: services
  deploy: false
  volumes: 
    config:
      enabled: false
      name: jellyseerr-config
      size: 200Mi
      access_modes:
        - ReadWriteOnce
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}

tautulli:
  name: tautulli
  namespace: services
  deploy: false
  volumes: 
    config:
      enabled: false
      name: tautulli-config
      size: 200Mi
      access_modes:
        - ReadWriteOnce
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}

media:
  name: media
  namespace: services
  deploy: false
  volumes:
    media:
      enabled: true
      name: media
      size: 300Gi
      access_modes:
        - ReadWriteMany
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}

radarr:
  name: radarr
  namespace: services
  deploy: true
  volumes:
    config:
      enabled: false
      name: radarr-config
      size: 512Mi
      access_modes:
        - ReadWriteOnce
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}
    api_key: ${api_keys["radarr_key"]}

renovate:
  name: renovate
  namespace: services
  deploy: true
  volumes:
    config:
      enabled: false
      name: renovate-config
      size: 512Mi
      access_modes:
        - ReadWriteOnce
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}
    gh_username: ${gh_username}
    gh_token: ${gh_token}

sonarr:
  name: sonarr
  namespace: services
  deploy: true
  volumes:
    config:
      enabled: false
      name: sonarr-config
      size: 512Mi
      access_modes:
        - ReadWriteOnce
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}
    api_key: ${api_keys["sonarr_key"]}


prowlarr:
  name: prowlarr
  namespace: services
  deploy: true
  volumes:
    config:
      enabled: false
      name: prowlarr-config
      size: 512Mi
      access_modes:
        - ReadWriteOnce
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}
    api_key: ${api_keys["prowlarr_key"]}


filebrowser:
  name: filebrowser
  namespace: services
  deploy: true
  volumes:
    config:
      enabled: false
      name: filebrowser-config
      size: 200Mi
      access_modes:
        - ReadWriteMany
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}

sabnzbd:
  name: sabnzbd
  namespace: services
  deploy: false
  volumes:
    config:
      enabled: false
      name: sabnzbd-config
      size: 200Mi
      access_modes:
        - ReadWriteOnce
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}

bazarr:
  name: bazarr
  namespace: services
  deploy: false
  volumes:
    config:
      enabled: false
      name: bazarr-config
      size: 200Mi
      access_modes:
        - ReadWriteOnce
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}

flood:
  name: flood
  namespace: services
  deploy: true
  volumes:
    config:
      enabled: false
      name: flood-config
      size: 200Mi
      access_modes:
        - ReadWriteOnce
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}
  
whisparr:
  name: whisparr
  namespace: services
  deploy: false
  volumes:
    config:
      enabled: false
      name: whisparr-config
      size: 200Mi
      access_modes:
        - ReadWriteMany
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}

readarr:
  name: readarr
  namespace: services
  deploy: false
  volumes:
    config:
      enabled: false
      name: readarr-config
      size: 200Mi
      access_modes:
        - ReadWriteMany
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}

mylar:
  name: mylar
  namespace: services
  deploy: false
  volumes:
    config:
      enabled: false
      name: mylar-config
      size: 200Mi
      access_modes:
        - ReadWriteMany
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}


kubeview:
  name: kubeview
  namespace: services
  deploy: false
  volumes:
    config:
      enabled: false
      name: kubeview-config
      size: 200Mi
      access_modes:
        - ReadWriteMany
  override:
    timezone: ${timezone}
    duckdns_domain: ${duckdns_domain}

