plex:

  env:
    ALLOWED_NETWORKS: ${allowed_networks}
    PGID: 1001
    PUID: 1001
    PLEX_CLAIM: ""
    PLEX_PREFERENCE_1: "FriendlyName=plexHome"
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Plex"
        gethomepage.dev/description: "Plex combines free movies & TV with your favorite streaming services and personal media"
        gethomepage.dev/group: "Media"
        gethomepage.dev/icon: "plex.png"
        gethomepage.dev/href: "https://plex.${duckdns_domain}.duckdns.org/web/index.html"
      enabled: true
      hosts:
        - host: "plex.${duckdns_domain}.duckdns.org"
          paths:
          - path: /
      tls:
        - hosts:
            - "plex.${duckdns_domain}.duckdns.org"
          secretName: tls-plex-ingress
