plex:

  env:
    ALLOWED_NETWORKS: ${allowed_networks}
    PGID: 1001
    PUID: 1001
    PLEX_CLAIM: ${plex_claim_token}
    PLEX_PREFERENCE_1: "FriendlyName=plexHome"
    TZ: ${timezone}


  nodeSelector:
    priority: ${priority}
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext,websecure
        # traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Plex"
        gethomepage.dev/description: "Plex combines free movies & TV with your favorite streaming services and personal media"
        gethomepage.dev/group: "Media"
        gethomepage.dev/icon: "plex.png"
        gethomepage.dev/href: "https://plex.${domain}/web/index.html"
        gethomepage.dev/widget.type: "plex"
        gethomepage.dev/widget.url: "http://plex.${namespace}.svc.cluster.local:32400"
        gethomepage.dev/widget.key: "${api_key}"
      enabled: true
      hosts:
        - host: "plex.${domain}"
          paths:
          - path: /
      tls:
        - hosts:
            - "plex.${domain}"
          secretName: tls-plex-ingress

  persistence:
    config:
      enabled: true
      existingClaim: plex-config
    downloads:
      enabled: true
      existingClaim: media    
    downloads-radarr:
      enabled: true
      existingClaim: media-radarr
      mountPath: /downloads/radarr
      subpath: radarr
  
  resources:
    requests: 
      gpu.intel.com/i915: "1" 
    limits: 
      gpu.intel.com/i915: "1" 
  #   limits:
  #     amd.com/gpu: 1