- name: Add hardened SSH config
  copy:
    dest: /etc/ssh/sshd_config
    src: ../files/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: Reload SSH

- name: Ensure firewalld is not installed
  package:
    name: firewalld
    state: absent

