- name: Add hardened SSH config
  copy:
    dest: /etc/ssh/sshd_config
    src: ../files/sshd_config
    owner: root
    group: root
    mode: 0600
  notify: Reload SSH

- name: Ensure firewalld is not installed
  package:
    name: firewalld
    state: absent

# - name: Disable firewalld
#   systemd:
#     name: firewalld
#     state: stopped
#     enabled: no
#     masked: yes

# - name: Add SSH port to public zone
#   firewalld:
#     zone: public
#     service: ssh
#     state: enabled
#     immediate: yes
#     permanent: no
  
# - name: Add permitted networks to public zone
#   firewalld:
#     zone: public
#     source: "{{ item }}"
#     state: enabled
#     immediate: yes
#     permanent: no
#   with_items: "{{ allowed_ssh_networks }}"


# - name: Add HTTPS port to public zone
#   firewalld:
#     zone: public
#     service: https
#     state: enabled
#     immediate: yes
#     permanent: no

# - name: Add Kubernetes port to public zone
#   firewalld:
#     zone: public
#     port: 6443/tcp
#     state: enabled
#     immediate: yes
#     permanent: no

# - name: Add monitor port to public zone
#   firewalld:
#     zone: public
#     port: 10250/tcp
#     state: enabled
#     immediate: yes
#     permanent: no

# - name: Add Home Assistant port to public zone
#   firewalld:
#     zone: public
#     port: 8123/tcp
#     state: enabled
#     immediate: yes
#     permanent: no

# - name: Add Ethernet  to public zone
#   firewalld:
#     zone: public
#     interface: eth0
#     state: enabled
#     immediate: yes
#     permanent: no

# - name: Add DNS port to public zone
#   firewalld:
#     zone: public
#     service: dns
#     state: enabled
#     immediate: yes
#     permanent: no


# - name: Create kubernetes_pods zone
#   firewalld:
#     zone: kubernetes_pods
#     state: present
#     permanent: yes

# - name: Reload Firewalld
#   service:
#     name: firewalld
#     state: reloaded

# - name: Add flannel subnet
#   firewalld:
#     zone: kubernetes_pods
#     state: enabled
#     source: 10.42.0.0/24
#     immediate: yes
#     permanent: no

# - name: Add flannel subnet
#   firewalld:
#     zone: kubernetes_pods
#     state: enabled
#     source: 10.42.1.0/24
#     immediate: yes
#     permanent: yes

# - name: Accept flannel subnet
#   firewalld:
#     zone: kubernetes_pods
#     state: "enabled"
#     target: "ACCEPT"
#     permanent: yes
