prowlarr:

  nodeSelector:
    priority: ${priority}
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Prowlarr"
        gethomepage.dev/description: "Prowlarr is an indexer manager/proxy for use with NZB and torrents"
        gethomepage.dev/group: "Aggregators"
        gethomepage.dev/icon: "prowlarr.png"
        gethomepage.dev/widget.type: "prowlarr"
        gethomepage.dev/widget.url: "http://prowlarr.${namespace}.svc.cluster.local:9696"
        gethomepage.dev/widget.key: "${api_key}"
      enabled: true
      hosts:
        - host: "prowlarr.${domain}"
          paths:
          - path: /
      tls:
        - hosts:
            - "prowlarr.${domain}"
          secretName: tls-prowlarr-ingress
  resources:
    requests:
      cpu: 15m
      memory: 476M
    limits:
      cpu: 181m
      memory: 928M