image:
  repository: lscr.io/linuxserver/jackett
  tag: 0.20.3889

ingress:
  main:
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    enabled: true
    hosts:
      - host: "jackett.${duckdns_domain}.duckdns.org"
        paths:
        - path: /
    tls:
      - hosts:
          - "jackett.${duckdns_domain}.duckdns.org"
        secretName: tls-jackett-ingress

initContainers:
  update-volume-permission:
    image: busybox
    command: ["sh", "-c", "chown -R 568:568 /config"]
    volumeMounts:
    - name: config
      mountPath: /config
    securityContext:
      runAsUser: 0

persistence:
  config:
    enabled: true
    existingClaim: jackett-config
  # downloads:
  #   enabled: true
  #   existingClaim: media