homepage:

  nodeSelector:
    priority: ${priority}
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd

      enabled: true
      hosts:
        - host: "home.${domain}"
          paths:
          - path: /
      tls:
        - hosts:
            - "home.${domain}"
          secretName: tls-home-ingress

  # All the config files for Homepage can be specified under their relevant config block.

  config:
    widgets:
      - resources:
          # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
          backend: resources
          expanded: true
          cpu: true
          memory: true
      - search:
          provider: google
          target: _blank
      ## Uncomment to enable Kubernetes integration
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - longhorn:
          expanded: true
          total: true
          labels: true
          nodes: true

    kubernetes:
      # change mode to 'cluster' to use RBAC service account
      mode: cluster
