homepage:

  nodeSelector:
    priority: ${priority}
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd

      enabled: true
      hosts:
        - host: "home.${domain}"
          paths:
          - path: /
      tls:
        - hosts:
            - "home.${domain}"
          secretName: tls-home-ingress
