homepage:

  nodeSelector:
    priority: ${priority}
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd

      enabled: true
      hosts:
        - host: "home.${domain}"
          paths:
          - path: /
      tls:
        - hosts:
            - "home.${domain}"
          secretName: tls-home-ingress

  # All the config files for Homepage can be specified under their relevant config block.

  config:
    settings:
      fiveColumns: true
      layout:
          Media:
            icon: mdi-movie-play
            # style: row
            # columns: 5
          Internal:
            icon: mdi-nas
            # style: row
            # columns: 5
          Aggregators:
            icon: mdi-briefcase-plus
            # style: row
            # columns: 5
          Monitoring:
            icon: mdi-safety-goggles
            # style: row
            # columns: 5
          # Services:
          #   icon: mdi-server-network
          #   style: columns
          Home Services:
            icon: mdi-home-lightbulb
            # style: row
            # columns: 5
    services:
      - Home Services:
          - homControl:
              href: http://localhost:8501
              icon: https://raw.githubusercontent.com/LarryGF/pi-k8s/homControl/docker/homControl/app/files/logo.png
    widgets:
      - resources:
          # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
          backend: kubernetes
          expanded: true
          cpu: true
          memory: true
      - search:
          provider: google
          target: _blank
      ## Uncomment to enable Kubernetes integration
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - longhorn:
          expanded: true
          total: true
          labels: true
          nodes: true


    kubernetes:
      # change mode to 'cluster' to use RBAC service account
      mode: cluster
