goldilocks:
  controller:
    nodeSelector:
      priority: ${priority}
    # controller.tolerations -- Tolerations for the controller pod

  dashboard:
    ingress:
      # dashboard.ingress.enabled -- Enables an ingress object for the dashboard.
      enabled: true

      # dashboard.ingress.ingressClassName -- From Kubernetes 1.18+ this field is supported in case your ingress controller supports it. When set, you do not need to add the ingress class as annotation.
      ingressClassName: "traefik"
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Goldilocks"
        gethomepage.dev/group: "Internal"
        gethomepage.dev/icon: "https://github.com/FairwindsOps/goldilocks/blob/master/img/goldilocks.svg"
      hosts:
        - host: goldilocks.${domain}
          paths:
            - path: /
              type: ImplementationSpecific

      tls:
       - secretName: tls-goldilocks-ingress
         hosts:
           - goldilocks.${domain}

    nodeSelector:
      priority: ${priority}
    tolerations: []
    affinity: {}
    # dashboard.topologySpreadConstraints -- Topology spread constraints for the dashboard pods
    topologySpreadConstraints: []
