nzbget:
  env:
    PGID: 1001
    PUID: 1001
    TZ: ${timezone}
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "NZBGet"
        gethomepage.dev/description: "NZBGet is a Usenet downloader client"
        gethomepage.dev/group: "Template Aggregators"
        gethomepage.dev/icon: "nzbget.png"
      enabled: true
      hosts:
        - host: "nzbget.${duckdns_domain}.duckdns.org"
          paths:
          - path: /
      tls:
        - hosts:
            - "nzbget.${duckdns_domain}.duckdns.org"
          secretName: tls-nzbget-ingress
