homepage:
  image:
    repository: ghcr.io/benphelps/homepage
    tag: v0.6.29

  # Enable RBAC. RBAC is necessary to use Kubernetes integration
  enableRbac: true

  env:
    LOG_LEVEL: debug
  
  serviceAccount:
    # Specify a different service account name
    name: homepage
    # Create service account. Needed when RBAC is enabled.
    create: true

  service:
    main:
      ports:
        http:
          port: 3000

  controller:
    strategy: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

   

    

  config:
    # To use an existing ConfigMap uncomment this line and specify the name
    # useExistingConfigMap: existing-homepage-configmap
    settings:
      title: "Home Dashboard"
      headerStyle: clean
      background: 
        image: https://wallpapercave.com/wp/wp8865987.jpg
        opacity: 20
      cardBlur: md
      quicklaunch:
        searchDescriptions: true
        hideInternetSearch: true
      hideVersion: true
      theme: dark
      providers:
        longhorn:
          url: http://longhorn-frontend.longhorn-system.svc.cluster.local
    bookmarks:
      - Developer:
          - Github Base Repo:
              - abbr: Repo
                href: https://github.com/LarryGF/pi-k8s
      

  persistence:
    logs:
      enabled: true
      type: emptyDir
      mountPath: /app/config/logs
