homepage:
  image:
    repository: ghcr.io/benphelps/homepage
    tag: v0.6.29

  # Enable RBAC. RBAC is necessary to use Kubernetes integration
  enableRbac: true

  env:
    LOG_LEVEL: debug
  
  serviceAccount:
    # Specify a different service account name
    name: homepage
    # Create service account. Needed when RBAC is enabled.
    create: true

  service:
    main:
      ports:
        http:
          port: 3000

  controller:
    strategy: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

    bookmarks:
      - Developer:
          - Github Base Repo:
              - abbr: Repo
                href: https://github.com/LarryGF/pi-k8s

    services: []


  persistence:
    logs:
      enabled: true
      type: emptyDir
      mountPath: /app/config/logs
