homepage:
  image:
    repository: ghcr.io/benphelps/homepage
    tag: 0.6.29

  # Enable RBAC. RBAC is necessary to use Kubernetes integration
  enableRbac: true

  env:
    LOG_LEVEL: debug
  
  serviceAccount:
    # Specify a different service account name
    name: homepage
    # Create service account. Needed when RBAC is enabled.
    create: true

  service:
    main:
      ports:
        http:
          port: 3000

  controller:
    strategy: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  # All the config files for Homepage can be specified under their relevant config block.
  config:
    # To use an existing ConfigMap uncomment this line and specify the name
    # useExistingConfigMap: existing-homepage-configmap
    settings:
      title: "Home Dashboard"
      headerStyle: clean
      quicklaunch:
        searchDescriptions: true
        hideInternetSearch: true
      hideVersion: true
      theme: dark
      providers:
        longhorn:
          url: http://longhorn-frontend.longhorn-system.svc.cluster.local
      layout:
        Media:
          icon: mdi-movie-play
          style: columns
        Internal:
          icon: mdi-nas
          style: columns
        Template Aggregators:
          icon: mdi-briefcase-plus
          style: columns
        Monitoring:
          icon: mdi-safety-goggles
          style: columns
        Services:
          icon: mdi-server-network
          style: columns
        Downloaders:
          icon: mdi-download
          style: columns
        

    bookmarks:
      - Developer:
          - Github Base Repo:
              - abbr: Repo
                href: https://github.com/LarryGF/pi-k8s

    services: []

    widgets:
      - resources:
          # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
          backend: resources
          expanded: true
          cpu: true
          memory: true
      - search:
          provider: google
          target: _blank
      ## Uncomment to enable Kubernetes integration
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - longhorn:
          expanded: true
          total: true
          labels: true
          nodes: true

    kubernetes:
      # change mode to 'cluster' to use RBAC service account
      mode: cluster

  persistence:
    logs:
      enabled: true
      type: emptyDir
      mountPath: /app/config/logs
