app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/oae/kaizoku
            tag: 1.6.1
            pullPolicy: IfNotPresent

          # -- environment variables.
          # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
          env:
            # -- Config dir
            DATA_FOLDER: "config"

        db:
          image:
            repository: postgres
            tag: alpine
            pullPolicy: IfNotPresent

          # -- environment variables.
          # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
          env:
            # -- Config dir
            POSTGRES_USER: kaizoku
            POSTGRES_DB: kaizoku
            POSTGRES_PASSWORD: kaizoku

        redis:
          image:
            repository: redis
            tag: 7-alpine
            pullPolicy: IfNotPresent
