app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/oae/kaizoku
            tag: 1.6.1
            pullPolicy: IfNotPresent

          # -- environment variables.
          # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
          env:
            # -- Config dir
            DATA_FOLDER: "config"
    db:
      containers:
        main:
          image:
            repository: ghcr.io/oae/kaizoku
            tag: 1.6.1
            pullPolicy: IfNotPresent

          # -- environment variables.
          # See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
          env:
            # -- Config dir
            DATA_FOLDER: "config" 
    redis:
      containers:
        main:
          image:
            repository: redis
            tag: 7-alpine
            pullPolicy: IfNotPresent



  # -- Configures service settings for the chart.
  service:
    main:
      ports:
        http:
          port: 3000
        # websocket:
        #   enabled: true
        #   port: 3012

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    main:
      enabled: true
      hosts:
        - host: chart-example.local
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
            - path: /notifications/hub/negotiate
              pathType: Prefix
              service:
                name: main
                port: http
            - path: /notifications/hub
              pathType: Prefix
              service:
                name: main
                port: websocket

  # -- Configure persistence settings for the chart under this key.
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 1Gi
      mountPath: /config
