intel-device-plugins-operator:
  nodeSelector:
    kubernetes.io/arch: amd64

  manager:
    image:
      hub: intel
      tag: ""
      pullPolicy: IfNotPresent

  kubeRbacProxy:
    image:
      hub: gcr.io
      hubRepo: kubebuilder
      tag: v0.14.1
      pullPolicy: IfNotPresent

  privateRegistry:
    registryUrl: ""
    registryUser: ""
    registrySecret: ""

intel-device-plugins-gpu:

  initImage:
    enable: true
    hub: intel
    tag: ""

  sharedDevNum: 1
  logLevel: 2
  resourceManager: false
  enableMonitoring: true
  allocationPolicy: "none"

  nodeSelector:
    intel.feature.node.kubernetes.io/gpu: 'true'

  nodeFeatureRule: true