samba:
  env:
    # -- Set the container timezone
    TZ: ${timezone}
    # SAMBA_WORKGROUP: NT-Domain-Name or Workgroup-Name. (default WORKGROUP)
    # SAMBA_SERVER_STRING: Server string is the equivalent of the NT Description field. (default Docker Samba Server)
    # SAMBA_LOG_LEVEL: Log level. (default 0)
    # SAMBA_FOLLOW_SYMLINKS: Allow to follow symlinks. (default yes)
    # SAMBA_WIDE_LINKS: Controls whether or not links in the UNIX file system may be followed by the server. (default yes)
    # SAMBA_HOSTS_ALLOW: Set of hosts which are permitted to access a service. (default 127.0.0.0/8 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16)
    # SAMBA_INTERFACES: Allows you to override the default network interfaces list.

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: false

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    my-hostpath:
      enabled: false
      type: hostPath
      hostPath: /share/samba/share1

  configmap:
    config:
      # -- Store samba configuration as a ConfigMap
      enabled: false
      # -- Samba configuration. See [image documentation](https://github.com/crazy-max/docker-samba#configuration) for more information.
      # @default -- See values.yaml
      data:
        config.yml: |
          auth:
            - user: foo
              group: foo
              uid: 1001
              gid: 1001
              password: bar

          global:
            - "force user = foo"
            - "force group = foo"

          share:
            - name: foo
              path: /share/samba/share1
              browsable: yes
              readonly: no
              guestok: no
              validusers: foo
              writelist: foo
              veto: no
