# home-assistant.yaml

image:
  repository: lscr.io/linuxserver/homeassistant
  tag: 2023.4.4

initContainers:
  copy-configmap:
    image: busybox
    command:
    - "sh"
    - "-c"
    - |
      cp /ha-config/configuration.yaml /config/configuration.yaml
    volumeMounts:
    - name: config
      mountPath: /config
    - name: config-custom
      mountPath: /ha-config
    
    securityContext:
      runAsUser: 0

ingress:
  main:
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    enabled: true
    hosts:
      - host: "ha.${duckdns_domain}.duckdns.org"
        paths:
        - path: /
    tls:
      - hosts:
          - "ha.${duckdns_domain}.duckdns.org"
        secretName: tls-ha-ingress

hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

persistence:
  config:
    enabled: true
    existingClaim: ha-config
  config-custom:
    enabled: true
    type: configMap
    name: config-file
  # usb:
  #   enabled: true
  #   type: hostPath
  #   hostPath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2434151-if00
  #   mountPath: /dev/ttyUSB0

nodeSelector:
  kubernetes.io/hostname: ${master_hostname}

securityContext:
  privileged: true

# addons: 
#   codeserver:
#     image:
#       repository: lscr.io/linuxserver/code-server
#     enabled: true
#     ingress:
#       main:
#         ingressClassName: traefik
#         annotations:
#           cert-manager.io/cluster-issuer: letsencrypt
#           traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
#         enabled: true
#         hosts:
#           - host: "code.ha.${duckdns_domain}.duckdns.org"
#             paths:
#             - path: /
#         tls:
#           - hosts:
#               - "code.ha.${duckdns_domain}.duckdns.org"
#             secretName: tls-ha-ingress
    
#     args:
#     - --auth
#     - none
#     - --user-data-dir
#     - "/config/.vscode"
    
#     git:
#       deployKeyBase64: ""

#     workingDir: "/config"

#     volumeMounts:
#     - name: config
#       mountPath: /config
