locals {
  category_mappings = {

  }
  common = {
    "title" : "Homer",
    "subtitle" : "Once you go black you never go back",
    "logo" : "logo.png",
    "header" : true,
    "footer" : "<span><img src=\"assets/gray0_ctp_on_line.png\" alt=\"footer\" style=\"display: block;margin-left: auto;margin-right: auto;\"></span>",
    "columns" : "4",
    "connectivityCheck" : true,
    "theme" : "default",
    "stylesheet" : [
      "assets/catppuccin-macchiato.css",
      "assets/catppuccin-latte.css"
    ],
    "defaults" : {
      "layout" : "columns",
      "colorTheme" : "dark"
    },

  }
  message = {
    "message" : {
      "style" : "is-info",
      "title" : "Homer Dashboard",
      "icon" : "fa fa-circle-dot",
      "content" : "This layout has been automatically generated by Terraform to match your setup."
    },

  }
  links = {
    "links" : [
      {
        "name" : "Link 1",
        "icon" : "fab fa-github",
        "url" : "https://github.com/bastienwirtz/homer",
        "target" : "_blank"
      },
      {
        "name" : "link 2",
        "icon" : "fas fa-book",
        "url" : "https://github.com/bastienwirtz/homer"
      },
      {
        "name" : "Second Page",
        "icon" : "fas fa-file-alt",
        "url" : "#page2"
      }
    ]
  }
  rest = {
    "services" : [
      {
        "name" : "//GitHub",
        "icon" : "fas fa-github",
        "items" : [
          {
            "name" : "Homer Theme",
            "logo" : "assets/tools/walkx.png",
            "subtitle" : "The official Homer Theme github!",
            "tag" : "github",
            "tagstyle" : "is-primary",
            "url" : "https://github.com/WalkxCode/Homer-Theme",
            "target" : "_blank"
          }
        ]
      },
      {
        "name" : "//Reddit",
        "icon" : "fas fa-reddit",
        "items" : [
          {
            "name" : "The original reddit post!",
            "logo" : "assets/tools/reddit.png",
            "subtitle" : "Yes... this is Homer.",
            "tag" : "reddit",
            "tagstyle" : "is-info",
            "url" : "https://www.reddit.com/r/selfhosted/comments/q9e82c/yes_this_is_homer_yes_i_spent_2_hours_customizing/",
            "target" : "_blank"
          }
        ]
      }
    ]
  }
  file = yamlencode(merge([local.common, local.rest, local.message, local.links]...))
}
