samba:
  image:
    # -- image repository
    repository: ghcr.io/crazy-max/samba
    # -- image tag
    tag: 4.18.5
    # -- image pull policy
    pullPolicy: Always

  # -- Configures service settings for the chart.
  # @default -- See values.yaml

