image:
  repository: lscr.io/linuxserver/heimdall
  tag: 2.5.6

ingress:
  main:
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    enabled: true
    hosts:
      - host: "heimdall.${duckdns_domain}.duckdns.org"
        paths:
        - path: /
    tls:
      - hosts:
          - "heimdall.${duckdns_domain}.duckdns.org"
        secretName: tls-heimdall-ingress

initContainers:
  update-volume-permission:
    image: busybox
    command: ["sh", "-c", "chown -R 568:568 /config"]
    volumeMounts:
    - name: config
      mountPath: /config
    securityContext:
      runAsUser: 0

persistence:
  config:
    enabled: true
    existingClaim: heimdall-config