app-template:
  defaultPodOptions:
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

  controllers:
    main:
      containers:
        main:
          image:
            repository: linuxserver/kavita
            tag: latest
            pullPolicy: IfNotPresent

          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false

  service:
    main:
      ports:
        http:
          port: 8080

  ingress:
    media:
      enabled: true
      className: "ingress-nginx"
      hosts:
        - host: sabnzbd.bjw-s.dev
          paths:
            - path: /
              service:
                name: main
                port: http

  persistence:
    media:
      existingClaim: nas-media
      globalMounts:
        - path: /data/nas-media
