app-template:
  defaultPodOptions:
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

  controllers:
    main:
      containers:
        main:
          image:
            repository: linuxserver/kavita
            tag: latest
            pullPolicy: IfNotPresent

          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false

  service:
    main:
      ports:
        http:
          port: 8080

  ingress:
    main:
      enabled: true
      className: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
      hosts:
        - host: kavita.${domain}
          paths:
            - path: /
              service:
                name: main
                port: http

  persistence:
    media:
      existingClaim: media
      globalMounts:
        - path: /downloads
    config:
      existingClaim: kavita-config
      globalMounts:
        - path: /config

