sabnzbd:
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "SABnzbd"
        gethomepage.dev/description: "Free and easy binary newsreader"
        gethomepage.dev/group: "Media"
        gethomepage.dev/icon: "sabnzbd-alt.png"
      enabled: true
      hosts:
        - host: "sabnzbd.${duckdns_domain}.duckdns.org"
          paths:
          - path: /
      tls:
        - hosts:
            - "sabnzbd.${duckdns_domain}.duckdns.org"
          secretName: tls-sabnzbd-ingress