readarr:

  nodeSelector:
    priority: ${priority}
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Readarr"
        gethomepage.dev/description: "Ebook and audiobook collection manager for Usenet and BitTorrent users"
        gethomepage.dev/group: "Template Aggregators"
        gethomepage.dev/icon: "readarr.png"
      enabled: true
      hosts:
        - host: "readarr.${duckdns_domain}.duckdns.org"
          paths:
          - path: /
      tls:
        - hosts:
            - "readarr.${duckdns_domain}.duckdns.org"
          secretName: tls-readarr-ingress