#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: b4bz/homer
  # @default -- chart.appVersion
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

initContainers:
  update-volume-permission:
    image: busybox
    command: ["sh", "-c", "chown -R 1001:1001 /config "]

    volumeMounts:
    - name: custom
      mountPath: /config
    securityContext:
      runAsUser: 0

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    enabled: true
    hosts:
      - host: "homer.${duckdns_domain}.duckdns.org"
        paths:
        - path: /
    tls:
      - hosts:
          - "homer.${duckdns_domain}.duckdns.org"
        secretName: tls-homer-ingress


securityContext:
  # -- Specify the user ID the application will run as
  runAsUser: 1001
  # -- Enable validation that the container must run as non-root user
  runAsNonRoot: true
  # -- Specify the group ID the application will run as
  runAsGroup: 1001

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml

persistence:
  custom:
    enabled: true
    mountPath: /www/assets
    existingClaim: homer-config

configmap:
  config:
    # -- Store homer configuration as a ConfigMap
    enabled: true
    # -- Homer configuration. See [image documentation](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md) for more information.
    # @default -- See values.yaml
    data:
      config.yml: |
        ${config}