filebrowser:
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "File Browser"
        gethomepage.dev/description: ""
        gethomepage.dev/group: "Storage"
        gethomepage.dev/icon: "filebrowser.png"
      enabled: true
      hosts:
        - host: "filebrowser.${duckdns_domain}.duckdns.org"
          paths:
          - path: /
      tls:
        - hosts:
            - "filebrowser.${duckdns_domain}.duckdns.org"
          secretName: tls-filebrowser-ingress
