filebrowser:

  nodeSelector:
    priority: ${priority}
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "File Browser"
        gethomepage.dev/description: ""
        gethomepage.dev/group: "Internal"
        gethomepage.dev/icon: "filebrowser.png"
      enabled: true
      hosts:
        - host: "filebrowser.${domain}.duckdns.org"
          paths:
          - path: /
      tls:
        - hosts:
            - "filebrowser.${domain}.duckdns.org"
          secretName: tls-filebrowser-ingress
