sonarr:

  nodeSelector:
    priority: ${priority}
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Sonarr"
        gethomepage.dev/description: "Sonarr is an internet PVR for Usenet and Torrents."
        gethomepage.dev/group: "Template Aggregators"
        gethomepage.dev/icon: "sonarr.png"
        gethomepage.dev/widget.type: "sonarr"
        gethomepage.dev/widget.url: "http://sonarr.${namespace}.svc.cluster.local:8989"
        gethomepage.dev/widget.key: "${api_key}"
      enabled: true
      hosts:
        - host: "sonarr.${domain}"
          paths:
          - path: /
      tls:
        - hosts:
            - "sonarr.${domain}"
          secretName: tls-sonarr-ingress

  metrics:
    prometheusRule:
      enabled: true