sonarr:
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: 3.0.10

  env:
    PGID: 1001
    PUID: 1001
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Sonarr"
        gethomepage.dev/description: "Sonarr is an internet PVR for Usenet and Torrents."
        gethomepage.dev/group: "Aggregators"
        gethomepage.dev/icon: "sonarr.png"
      enabled: true
      hosts:
        - host: "sonarr.${duckdns_domain}.duckdns.org"
          paths:
          - path: /
      tls:
        - hosts:
            - "sonarr.${duckdns_domain}.duckdns.org"
          secretName: tls-sonarr-ingress

  initContainers:
    update-volume-permission:
      image: busybox
      command: ["sh", "-c", "chmod -R 777 /config && mkdir -p /downloads/sonarr && chown -R 1001:1001 /downloads/sonarr"]

      volumeMounts:
      - name: config
        mountPath: /config
      - name: downloads
        mountPath: /downloads
      securityContext:
        runAsUser: 0

  persistence:
    config:
      enabled: true
      existingClaim: sonarr-config
    downloads:
      enabled: true
      existingClaim: media