sonarr:
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Sonarr"
        gethomepage.dev/description: "Sonarr is an internet PVR for Usenet and Torrents."
        gethomepage.dev/group: "Template Aggregators"
        gethomepage.dev/icon: "sonarr.png"
        gethomepage.dev/widget.type: "sonarr"
        gethomepage.dev/widget.url: "http://sonarr.${namespace}.svc.cluster.local:8989"
        gethomepage.dev/widget.key: "${api_key}"
      enabled: true
      hosts:
        - host: "sonarr.${duckdns_domain}.duckdns.org"
          paths:
          - path: /
      tls:
        - hosts:
            - "sonarr.${duckdns_domain}.duckdns.org"
          secretName: tls-sonarr-ingress
