networkPolicies:
  enabled: false
  # Available types: k3s, rke2, rke1
  type: "k3s"

ingress:
  enabled: true
  ingressClassName: traefik
  host: "longhorn.${domain}"
  tls: true
  secureBackends: false
  tlsSecret: tls-longhorn-ingress
  path: /

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Longhorn"
    gethomepage.dev/description: ""
    gethomepage.dev/group: "Internal"
    gethomepage.dev/icon: "longhorn.png"


persistence:
  defaultClass: true
  defaultClassReplicaCount: 1

  
defaultSettings:
  defaultLonghornStaticStorageClass: longhorn
  createDefaultDiskLabeledNodes: true
  defaultReplicaCount: 1
  defaultDataPath: ${default_data_path}

longhornUI:
  nodeSelector:
    priority: critical
