pihole:
  virtualHost: pi.hole
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Pi-hole"
      gethomepage.dev/description: "Network-wide Ad Blocking"
      gethomepage.dev/group: "Internal"
      gethomepage.dev/icon: "pi-hole.png"
      # gethomepage.dev/widget.type: "jellyseerr"
      # gethomepage.dev/widget.url: "http://jellyseerr.${namespace}.svc.cluster.local:7878"
      # gethomepage.dev/widget.key: "${api_key}"
    path: /
    hosts:
      # virtualHost (default value is pi.hole) will be appended to the hosts
      - "pihole.${duckdns_domain}.duckdns.org"
    tls: 
      - hosts:
          - "pihole.${duckdns_domain}.duckdns.org"
        secretName: tls-pihole-ingress


  # -- Administrator password when not using an existing secret (see below)
  adminPassword: "admin"

  # -- Use an existing secret for the admin password.
  admin:
    # -- Specify an existing secret to use as admin password
    existingSecret: ""
    # -- Specify the key inside the secret to use
    passwordKey: "password"


  dnsmasq:
    # -- Add upstream dns servers. All lines will be added to the pihole dnsmasq configuration
    upstreamServers: []
    # - server=/foo.bar/192.168.178.10
    # - server=/bar.foo/192.168.178.11

    # -- Add custom dns entries to override the dns resolution. All lines will be added to the pihole dnsmasq configuration.
    customDnsEntries: []
    - address=/${duckdns_domain}/${master_ip}
    # - address=/bar.foo/192.168.178.11

    # -- Dnsmasq reads the /etc/hosts file to resolve ips. You can add additional entries if you like
    additionalHostsEntries: []
    # - 192.168.0.3     host4
    # - 192.168.0.4     host5

    # -- Static DHCP config
    staticDhcpEntries: []
    # staticDhcpEntries:
    # - dhcp-host=MAC_ADDRESS,IP_ADDRESS,HOSTNAME

    # -- Other options
    customSettings:
    # otherSettings:
    # - rebind-domain-ok=/plex.direct/

    # -- Here we specify custom cname entries that should point to `A` records or
    # elements in customDnsEntries array.
    # The format should be:
    #  - cname=cname.foo.bar,foo.bar
    #  - cname=cname.bar.foo,bar.foo
    #  - cname=cname record,dns record
    customCnameEntries: []
    # Here we specify custom cname entries that should point to `A` records or
    # elements in customDnsEntries array.
    # The format should be:
    #   - cname=cname.foo.bar,foo.bar
    #   - cname=cname.bar.foo,bar.foo
    #   - cname=cname record,dns record
