  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #
tautulli:
  image:
    # -- image repository
    repository: lscr.io/linuxserver/tautulli
    # -- image pull policy
    pullPolicy: IfNotPresent

  # -- environment variables.
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: ${timezone}

  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 8181

  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Tautulli"
        gethomepage.dev/description: "A Python based monitoring and tracking tool for Plex"
        gethomepage.dev/group: "Media"
        gethomepage.dev/icon: "tautulli.png"
      enabled: true
      hosts:
        - host: "tautulli.${duckdns_domain}.duckdns.org"
          paths:
          - path: /
      tls:
        - hosts:
            - "tautulli.${duckdns_domain}.duckdns.org"
          secretName: tls-tautulli-ingress

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: true
      existingClaim: tautulli-config