tautulli:
  env:
    TZ: ${timezone}

  nodeSelector:
    priority: ${priority}
  resources:
    requests:
      cpu: 22m
      memory: 127M
    limits:
      cpu: 212m
      memory: 247M
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Tautulli"
        gethomepage.dev/description: "A Python based monitoring and tracking tool for Plex"
        gethomepage.dev/group: "Media"
        gethomepage.dev/icon: "tautulli.png"
        gethomepage.dev/widget.type: "tautulli"
        gethomepage.dev/widget.url: "http://tautulli.${namespace}.svc.cluster.local:8181"
        gethomepage.dev/widget.key: "${api_key}"
      enabled: true
      hosts:
        - host: "tautulli.${domain}"
          paths:
          - path: /
      tls:
        - hosts:
            - "tautulli.${domain}"
          secretName: tls-tautulli-ingress
