plex:
  image:
    repository: ghcr.io/hotio/plex
    tag: release-1.32.7.7621-871adbd44
    pullPolicy: Always

  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  initContainers:
    update-volume-permission:
      image: busybox
      command: ["sh", "-c", "chmod -R 777 /config"]

      volumeMounts:
      - name: config
        mountPath: /config
      securityContext:
        runAsUser: 0


