plex:
  image:
    repository: lscr.io/linuxserver/plex
    tag: latest


  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  initContainers:
    update-volume-permission:
      image: busybox
      command: ["sh", "-c", "chmod -R 777 /config"]

      volumeMounts:
      - name: config
        mountPath: /config
      securityContext:
        runAsUser: 0

  persistence:
    config:
      enabled: true
      existingClaim: plex-config
    downloads:
      enabled: true
      existingClaim: media

  nodeSelector:
    # kubernetes.io/hostname: ${master_hostname}
    kubernetes.io/arch: amd64