plex:
  image:
    repository: ghcr.io/hotio/plex
    tag: latest
    pullPolicy: Always

  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  initContainers:
    update-volume-permission:
      image: busybox
      command: ["sh", "-c", "chmod -R 777 /config"]

      volumeMounts:
      - name: config
        mountPath: /config
      securityContext:
        runAsUser: 0


  nodeSelector:
    # kubernetes.io/hostname: ${master_hostname}
    kubernetes.io/arch: amd64