sabnzbd:
  image:
    repository: cr.hotio.dev/hotio/sabnzbd
    tag: release-4.2.1

  initContainers:
    update-volume-permission:
      image: busybox
      command: ["sh", "-c", "chmod -R 777 /config  && mkdir -p /downloads/sabnzbd && chown 1001:1001 /downloads/sabnzbd"]

      volumeMounts:
      - name: config
        mountPath: /config
      - name: downloads 
        mountPath: /downloads 
      securityContext:
        runAsUser: 0


#  # VPN side-car
#   addons:
#     vpn:
#       enabled: false
#       type: wireguard
#       wireguard:
#         image:
#           tag: v1.0.20210914

#       # -- Reference an existing secret that contains the VPN configuration file
#       # The chart expects it to be present under the `vpnConfigfile` key.
#       configFileSecret: vpnconfig
#       scripts:
#         up: |-
#           #!/bin/bash
#           echo "connected" > /shared/vpnstatus

#         down: |-
#           #!/bin/bash
#           echo "disconnected" > /shared/vpnstatus