sabnzbd:
  image:
    repository: cr.hotio.dev/hotio/sabnzbd
    tag: latest

  env:
    PGID: 1001
    PUID: 1001
    TZ: ${timezone}
    
  initContainers:
    update-volume-permission:
      image: busybox
      command: ["sh", "-c", "chmod -R 777 /config  && mkdir -p /downloads/sabnzbd && chown -R 1001:1001 /downloads/sabnzbd"]

      volumeMounts:
      - name: config
        mountPath: /config
      - name: downloads 
        mountPath: /downloads 
      securityContext:
        runAsUser: 0

  persistence:
    config:
      enabled: true
      existingClaim: sabnzbd-config
    downloads:
      enabled: true
      existingClaim: media