---
# Disable SWAP
- name: Disable Raspbian SWAP service
  systemd:
    name: dphys-swapfile
    state: stopped
    enabled: false
    masked: true

- name: Disable SWAP
  command: /sbin/swapoff -a
  when:
    - ansible_swaptotal_mb > 1

# Time
- name: Set timezone
  timezone:
    name: "{{ timezone }}"

# DNS
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update the /etc/hosts file with node name
  lineinfile:
    path: "/etc/hosts"
    regexp: "^127.0.1.1.*"
    line: "127.0.1.1\t{{ inventory_hostname }}"
    state: present
    backup: true

- name: Configure Cloudflare DNS
  copy:
    src: "resolv.conf"
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    mode: 0644

# Disable packages and services
- name: Ensure chrony is not installed
  package:
    name: chrony
    state: absent

- name: Stop and disable systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
    masked: true

- name: Stop NetworkManager from modifying resolv.conf
  lineinfile:
    path: "/etc/NetworkManager/NetworkManager.conf"
    state: present
    line: "dns=none"
    regexp: "^dns=.*"
    insertafter: '^\[main\]'
  notify: restart networkmanager

# Upgrade System
- name: Import upgrade role
  import_role:
    name: basic-upgrade

# Install Dependencies
- name: Import install role
  import_role:
    name: basic-install

# GPU
- name: Detect Graphics Card
  shell: lspci | grep -i 'VGA\|Display'
  register: gpu_check
  changed_when: false
  ignore_errors: true

- name: Set fact for GPU presence
  set_fact:
    gpu_present: "{{ 'VGA' in gpu_check.stdout or 'Display' in gpu_check.stdout }}"

- name: Install Intel GPU drivers
  apt:
    name: intel-media-va-driver
    state: present
  when: gpu_present and 'Intel' in gpu_check.stdout

- name: Import amd-gpu role
  import_role:
    name: gpu-amd
  when: gpu_present and 'AMD' in gpu_check.stdout

# Log rotation
- name: Set up logrotate for daemon.log and syslog
  copy:
    dest: "/etc/logrotate.d/large_logfiles"
    content: |
      /var/log/daemon.log
      /var/log/syslog
      {
        rotate 1
        weekly
        missingok
        notifempty
        compress
        delaycompress
        sharedscripts
        postrotate
          /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
        endscript
      }

- name: Increase system watchers
  become: true
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_set: yes
    ignoreerrors: no
  loop:
    - { name: 'fs.inotify.max_user_instances', value: '1280' }
    - { name: 'fs.inotify.max_user_watches', value: '1235100' }
