image:
  repository: lscr.io/linuxserver/prowlarr
  tag: latest

env:
  PGID: 1001
  PUID: 1001
  
ingress:
  main:
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Prowlarr"
      gethomepage.dev/description: "Prowlarr is an indexer manager/proxy for use with NZB and torrents"
      gethomepage.dev/group: "Aggregators"
      gethomepage.dev/icon: "prowlarr.png"
    enabled: true
    hosts:
      - host: "prowlarr.${duckdns_domain}.duckdns.org"
        paths:
        - path: /
    tls:
      - hosts:
          - "prowlarr.${duckdns_domain}.duckdns.org"
        secretName: tls-prowlarr-ingress

initContainers:
  update-volume-permission:
    image: busybox
    command: ["sh", "-c", "chmod -R 777 /config"]

    volumeMounts:
    - name: config
      mountPath: /config
    securityContext:
      runAsUser: 0

persistence:
  config:
    enabled: true
    existingClaim: prowlarr-config