locals {

  common = {
    "title" : "Homer",
    "subtitle" : "Once you go black you never go back",
    "logo" : "logo.png",
    "header" : true,
    "footer" : "<span><img src=\"assets/gray0_ctp_on_line.png\" alt=\"footer\" style=\"display: block;height:20px;margin-left: auto;margin-right: auto;\"></span>",
    "columns" : "4",
    "connectivityCheck" : true,
    "theme" : "default",
    "stylesheet" : [
      "assets/catppuccin-mocha.css",
      "assets/catppuccin-latte.css"
    ],
    "defaults" : {
      "layout" : "list",
      "colorTheme" : "dark"
    }

  }
  message = {
    "message" : {
      "style" : "is-info",
      "title" : "Homer Dashboard",
      "icon" : "fa fa-circle-dot",
      "content" : "This layout has been automatically generated by Terraform to match your setup."
    },

  }
  links = {
    "links" : [
      {
        "name" : "Link 1",
        "icon" : "fab fa-github",
        "url" : "https://github.com/bastienwirtz/homer",
        "target" : "_blank"
      },
      {
        "name" : "link 2",
        "icon" : "fas fa-book",
        "url" : "https://github.com/bastienwirtz/homer"
      },
      {
        "name" : "Second Page",
        "icon" : "fas fa-file-alt",
        "url" : "#page2"
      }
    ]
  }
}
