kubeview:
  limitNamespace: false

  replicaCount: 1

  image:
    repository: ghcr.io/benc-uk/kubeview
    tag: 0.1.31
    pullPolicy: Always



  # If you want to expose the kubeview service directly
  loadBalancer:
    IP: ""
    enabled: true

  # Note.
  # If both ingress and loadbalancer are disabled, a ClusterIP service will be created

  # Mostly never need to change these
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}
