ingress:
  enabled: true
  ingressClassName: traefik
  host: "longhorn.${domain}.duckdns.org"
  tls: true
  secureBackends: false
  tlsSecret: tls-longhorn-ingress
  path: /

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  #  kubernetes.io/ingress.class: nginx
  #  kubernetes.io/tls-acme: true

persistence:
  defaultClassReplicaCount: 1
  
defaultSettings:
  defaultLonghornStaticStorageClass: longhorn
  createDefaultDiskLabeledNodes: true
  defaultReplicaCount: 1
  defaultDataPath: ${default_data_path}
