---
- name: Basic configuration
  hosts: all
  become: true
  roles:
    - role: basic
  tags:
    - basic

- name: Harden server
  become: true
  hosts: all
  roles:
    - role: harden
  tags:
    - harden

- name: Kubernetes installation prerequisites
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: prereq
    - role: raspberrypi
  tags:
    - prereq

- name: Kubernetes installation download
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: download
  tags:
    - download
    - kubernetes

- name: Kubernetes master installation
  become: true
  hosts: master
  roles:
    - role: k3s/master
  tags:
    - kubernetes
    - master

- name: Kubernetes agent installation
  become: true
  hosts: agent
  roles:
    - role: k3s/node
  tags:
    - kubernetes
    - agent

- name: Kubernetes config sync to host
  hosts: master
  roles:
    - role: sync
  tags:
    - kubernetes

- name: Configure storage nodes
  hosts: storage
  become: true
  roles:
    - storage
  tags:
    - kubernetes
    - storage

# - name: Install and Configure ZeroTier
#   hosts: zerotier
#   become: true
#   roles:
#     - zerotier
#   tags:
#     - zerotier
