---
- name: Basic configuration
  hosts: all
  # become: yes
  roles:
    - role: basic
  tags:
    - basic

- name: Harden server
  hosts: all
  # become: yes
  roles:
    - role: harden
  tags:
    - harden
    
- name: Kubernetes installation prerequisites
  hosts: all
  gather_facts: yes
  # become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi
  tags:
    - kubernetes

- name: Kubernetes master installation 
  hosts: master
  # become: yes
  roles:
    - role: k3s/master
  tags:
    - kubernetes
    - master

- name: Kubernetes agent installation
  hosts: agent
  # become: yes
  roles:
    - role: k3s/node
  tags:
    - kubernetes
    - agent

- name: Kubernetes config sync to host
  hosts: master
  roles:
    - role: sync
  tags:
    - kubernetes

- name: Configure storage nodes
  hosts: storage
  become: yes
  roles:
  - storage
  tags:
    - storage