home-assistant:
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Home Assistant"
        gethomepage.dev/description: ""
        gethomepage.dev/group: "Services"
        gethomepage.dev/icon: "home-assistant-alt.png"
      enabled: true
      hosts:
        - host: "ha.${duckdns_domain}.duckdns.org"
          paths:
          - path: /
      tls:
        - hosts:
            - "ha.${duckdns_domain}.duckdns.org"
          secretName: tls-ha-ingress

  nodeSelector:
    kubernetes.io/hostname: ${master_hostname}

  addons:
    codeserver:
      image:
        repository: codercom/code-server
        tag: 4.11.0
      enabled: true
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "HA Code Server"
          gethomepage.dev/description: ""
          gethomepage.dev/group: "Services"
          gethomepage.dev/icon: "code.png"
        hosts:
        - host: codeha.${duckdns_domain}.duckdns.org
          paths:
            - path: /
        tls:
        - secretName: tls-code-ha-ingress
          hosts:
            - codeha.${duckdns_domain}.duckdns.org

      args:
      - --auth
      - none
      - --user-data-dir
      - "/config/.vscode"
      
      workingDir: "/config"

      volumeMounts:
      - name: config
        mountPath: /config
