home-assistant:
  env:
    PGID: 1001
    PUID: 1001
    TZ: ${timezone}
    PYTHONUSERBASE: /config/deps

  nodeSelector:
    priority: ${priority}
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Home Assistant"
        gethomepage.dev/description: ""
        gethomepage.dev/group: "Home Services"
        gethomepage.dev/icon: "home-assistant-alt.png"
      enabled: true
      hosts:
        - host: "ha.${domain}"
          paths:
          - path: /
      tls:
        - hosts:
            - "ha.${domain}"
          secretName: tls-ha-ingress


  addons:
    codeserver:
      image:
        repository: codercom/code-server
        tag: 4.18.0
      enabled: true
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "HA Code Server"
          gethomepage.dev/description: ""
          gethomepage.dev/group: "Internal"
          gethomepage.dev/icon: "code.png"
        hosts:
        - host: codeha.${domain}
          paths:
            - path: /
        tls:
        - secretName: tls-code-ha-ingress
          hosts:
            - codeha.${domain}

      args:
      - --auth
      - none
      - --user-data-dir
      - "/config/.vscode"
      
      workingDir: "/config"

      volumeMounts:
      - name: config
        mountPath: /config

  persistence:
    config:
      enabled: true
      existingClaim: ha-config
    config-custom:
      enabled: true
      type: configMap
      name: config-file
    # usb:
    #   enabled: true
    #   type: hostPath
    #   hostPath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2434151-if00
    #   mountPath: /dev/ttyUSB0
  resources:
    limits: 
      cpu: "0.5"
      memory: 1.5Gi
    requests: 
      cpu: "0.1"
      memory: 500Mi
