mylar:
  image:
    repository: lscr.io/linuxserver/mylar3
    tag: latest

  env:
    PGID: 1001
    PUID: 1001
    

  initContainers:
    update-volume-permission:
      image: busybox
      command: ["sh", "-c", "chmod -R 777 /config && mkdir -p /downloads/mylar/comics /downloads/mylar/downloads" ]

      volumeMounts:
      - name: config
        mountPath: /config
      - name: downloads
        mountPath: /downloads
      securityContext:
        runAsUser: 0

  persistence:
    config:
      enabled: true
      existingClaim: mylar-config
    downloads:
      enabled: true
      existingClaim: media