radarr:

  nodeSelector:
    priority: ${priority}
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Whisparr"
        gethomepage.dev/description: "Adult movie collection manager for Usenet and BitTorrent users."
        gethomepage.dev/group: "Aggregators"
        gethomepage.dev/icon: "whisparr.png"
      enabled: true
      hosts:
        - host: "whisparr.${domain}"
          paths:
          - path: /
      tls:
        - hosts:
            - "whisparr.${domain}"
          secretName: tls-whisparr-ingress