image:
  repository: lscr.io/linuxserver/heimdall
  tag: 2.5.6

ingress:
  main:
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    enabled: true
    hosts:
      - host: "heimdall.${duckdns_domain}.duckdns.org"
        paths:
        - path: /
    tls:
      - hosts:
          - "heimdall.${duckdns_domain}.duckdns.org"
        secretName: tls-heimdall-ingress

persistence:
  config:
    enabled: true
    existingClaim: heimdall-config