rtorrent-flood:
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Flood"
        gethomepage.dev/description: "A beautiful web UI for various torrent clients."
        gethomepage.dev/group: "Downloaders"
        gethomepage.dev/icon: "flood.png"
        gethomepage.dev/ping: "http://flood-rtorrent-flood.${namespace}.svc.cluster.local:3000"
        gethomepage.dev/widget.type: "flood"
        gethomepage.dev/widget.url: "http://flood-rtorrent-flood.${namespace}.svc.cluster.local:3000"
        gethomepage.dev/widget.username: "admin"
        gethomepage.dev/widget.password: "admin"

      enabled: true
      hosts:
        - host: "flood.${duckdns_domain}.duckdns.org"
          paths:
          - path: /
      tls:
        - hosts:
            - "flood.${duckdns_domain}.duckdns.org"
          secretName: tls-flood-ingress