mylar:

  nodeSelector:
    priority: ${priority}
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Mylar"
        gethomepage.dev/description: "Automated Comic Book (cbr/cbz) downloader for use with NZB and torrents "
        gethomepage.dev/group: "Template Aggregators"
        gethomepage.dev/icon: "mylar.png"
      enabled: true
      hosts:
        - host: "mylar.${domain}.duckdns.org"
          paths:
          - path: /
      tls:
        - hosts:
            - "mylar.${domain}.duckdns.org"
          secretName: tls-mylar-ingress