mylar:

  nodeSelector:
    priority: ${priority}
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        %{~ if mfa ~}
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd
        %{~ endif ~}
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Mylar"
        gethomepage.dev/description: "Automated Comic Book (cbr/cbz) downloader for use with NZB and torrents "
        gethomepage.dev/group: "Aggregators"
        gethomepage.dev/icon: "mylar.png"
      enabled: true
      hosts:
        - host: "mylar.${domain}"
          paths:
          - path: /
      tls:
        - hosts:
            - "mylar.${domain}"
          secretName: tls-mylar-ingress

  persistence:
    config:
      enabled: true
      existingClaim: mylar-config
    downloads:
      enabled: true
      existingClaim: media