mylar:
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Mylar"
        gethomepage.dev/description: "Mylar is an automated Comic Book (cbr/cbz) downloader program for use with NZB and torrents "
        gethomepage.dev/group: "Template Aggregators"
        gethomepage.dev/icon: "mylar.png"
      enabled: true
      hosts:
        - host: "mylar.${duckdns_domain}.duckdns.org"
          paths:
          - path: /
      tls:
        - hosts:
            - "mylar.${duckdns_domain}.duckdns.org"
          secretName: tls-mylar-ingress