bazarr:
  env:
    PGID: 1001
    PUID: 1001
    TZ: ${timezone}
  
  nodeSelector:
    priority: ${priority}
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Bazarr"
        gethomepage.dev/description: "Bazarr is a companion application to Sonarr and Radarr that manages and downloads subtitles"
        gethomepage.dev/group: "Template Aggregators"
        gethomepage.dev/icon: "bazarr.png"
        gethomepage.dev/widget.type: "bazarr"
        gethomepage.dev/widget.url: "http://bazarr.${namespace}.svc.cluster.local:7878"
        gethomepage.dev/widget.key: "${api_key}"
      enabled: true
      hosts:
        - host: "bazarr.${domain}"
          paths:
          - path: /
      tls:
        - hosts:
            - "bazarr.${domain}"
          secretName: tls-bazarr-ingress

  persistence:
    config:
      enabled: true
      existingClaim: bazarr-config
    downloads:
      enabled: true
      existingClaim: media
    downloads-radarr:
      enabled: true
      existingClaim: media-radarr
      mountPath: /downloads/radarr
      subpath: radarr