bazarr:
  env:
    PGID: 1001
    PUID: 1001
    TZ: ${timezone}
  
  nodeSelector:
    priority: ${priority}
    
  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Bazarr"
        gethomepage.dev/description: "Bazarr is a companion application to Sonarr and Radarr that manages and downloads subtitles"
        gethomepage.dev/group: "Internal"
        gethomepage.dev/icon: "bazarr.png"
      enabled: true
      hosts:
        - host: "bazarr.${domain}"
          paths:
          - path: /
      tls:
        - hosts:
            - "bazarr.${domain}"
          secretName: tls-bazarr-ingress
