grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-prometheus:9090
        access: proxy
        isDefault: true
      - name: Alertmanager
        type: alertmanager
        url: http://prometheus-alertmanager:9093
        access: proxy
        jsonData:
          implementation: prometheus
          handleGrafanaManagedAlerts: false
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway
        jsonData:
          maxLines: 1000

  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Admin
    panels:
      disable_sanitize_html: true

  plugins:
    - grafana-piechart-panel

loki-mixin:
  fullnameOverride: loki-mixin
  grafana:
    folder: Loki

alertmanager-mixin:
  fullnameOverride: alertmanager-mixin
  grafana:
    folder: Prometheus

kube-state-metrics-mixin:
  fullnameOverride: kube-state-metrics-mixin
  grafana:
    folder: Prometheus

prometheus-operator-mixin:
  fullnameOverride: prometheus-operator-mixin
  grafana:
    folder: Prometheus

promtail-mixin:
  fullnameOverride: promtail-mixin
  grafana:
    folder: Loki

tempo-mixin:
  fullnameOverride: tempo-mixin
  grafana:
    folder: Tempo