prowlarr:
  image:
    repository: lscr.io/linuxserver/prowlarr
    tag: latest

  env:
    PGID: 1001
    PUID: 1001
    TZ: ${timezone}
    

  initContainers:
    update-volume-permission:
      image: busybox
      command: ["sh", "-c", "chmod -R 777 /config"]

      volumeMounts:
      - name: config
        mountPath: /config
      securityContext:
        runAsUser: 0

  persistence:
    config:
      enabled: true
      existingClaim: prowlarr-config

  metrics:
    enabled: true