portainer:
  nodeSelector:
    priority: ${priority}

  feature:
    flags: ""

  ingress:
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "Portainer"
      gethomepage.dev/description: ""
      gethomepage.dev/group: "Internal"
      gethomepage.dev/icon: "portainer.png"
      gethomepage.dev/widget.type: "portainer"
      gethomepage.dev/widget.env: "1"
      gethomepage.dev/widget.url: "http://portainer.${namespace}.svc.cluster.local:9443"
      gethomepage.dev/widget.key: "${api_key}"
    enabled: true
    hosts:
      - host: "portainer.${domain}"
        paths:
        - path: /
    tls:
      - hosts:
          - "portainer.${domain}"
        secretName: tls-portainer-ingress
