portainer:

  feature:
    flags: ""

  ingress:
    main:
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        traefik.ingress.kubernetes.io/router.entrypoints: websecure-ext
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Portainer"
        gethomepage.dev/description: ""
        gethomepage.dev/group: "Internal"
        gethomepage.dev/icon: "portainer.png"
      enabled: true
      hosts:
        - host: "portainer.${duckdns_domain}.duckdns.org"
          paths:
          - path: /
      tls:
        - hosts:
            - "portainer.${duckdns_domain}.duckdns.org"
          secretName: tls-portainer-ingress
