name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push api
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./control-ui/api
        push: true
        tags: larryGF/control-ui-api:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Build and push ui
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./control-ui/ui
        push: true
        tags: larryGF/control-ui-ui:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
